# Generated by Django 3.1.2 on 2020-10-17 08:19

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes_app', '0006_note_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='note',
            name='img',
            field=models.ImageField(null=True, upload_to='notes-img'),
        ),
    ]
