# Generated by Django 3.1.2 on 2020-10-17 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes_app', '0007_auto_20201017_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='notes-img'),
        ),
    ]
