# Generated by Django 3.1.2 on 2020-10-12 07:03

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('headline', models.CharField(max_length=50)),
                ('bio', models.TextField()),
                ('slug', models.SlugField(blank=True, null=True)),
                ('img', models.ImageField(upload_to='profile_img')),
                ('join_date', models.DateField(default=datetime.datetime(2020, 10, 12, 10, 3, 55, 369556))),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
