# Generated by Django 3.1.2 on 2020-10-12 07:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201012_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='join_date',
            field=models.DateField(default=datetime.datetime(2020, 10, 12, 10, 27, 27, 325665)),
        ),
    ]
