# Generated by Django 3.1.2 on 2020-10-12 08:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20201012_1052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='profile',
            name='join_date',
            field=models.DateField(default=datetime.datetime(2020, 10, 12, 11, 33, 12, 287649)),
        ),
    ]
