# Generated by Django 3.1.2 on 2020-10-17 08:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20201012_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='join_date',
            field=models.DateField(default=datetime.datetime(2020, 10, 17, 11, 19, 2, 844087)),
        ),
    ]
